/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectolabo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.Timer;

/**
 *
 * @author alexo
 */
public class Desafios extends javax.swing.JDialog {

    /**
     * Creates new form Desafios
     */
    
    private String pregunta;
    private int opCorrecta;
    private int tiempo;
    private String[] op;
    private boolean acierto = false;
    private ButtonGroup group = new ButtonGroup();
    
    public Desafios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public Desafios(java.awt.Frame parent, boolean modal, String pregunta, int opCorrecta, int tiempo, String[] op) {
        super(parent, modal);
        initComponents();
        
        //Inicializamos las variables
        this.pregunta = pregunta;
        this.opCorrecta = opCorrecta;
        this.tiempo = tiempo;
        this.op = op;
        this.group.add(Op1);
        this.group.add(Op2);
        this.group.add(Op3);
        this.group.add(Op4);
        
        // Establecer la pregunta y las opciones
        this.setPregunta();
        this.setOp();
        
        setLocationRelativeTo(null);
        
        Timer timer = new Timer(tiempo * 1000, new ActionListener() {//creamos un temporizador
            public void actionPerformed(ActionEvent e) {
                acierto = false;
                dispose();
            }
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    private void setPregunta(){
        this.Pregunta.setText(pregunta);
    }
    
    private void setOp(){
        this.Op1.setText(op[0]);
        this.Op2.setText(op[1]);
        this.Op3.setText(op[2]);
        this.Op4.setText(op[3]);
    }
    
    public boolean isAcierto() {
        return acierto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pregunta = new javax.swing.JLabel();
        Op1 = new javax.swing.JRadioButton();
        Op2 = new javax.swing.JRadioButton();
        Op3 = new javax.swing.JRadioButton();
        Op4 = new javax.swing.JRadioButton();
        Enviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Desafio");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 22, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/DesafioImagen/desafio.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, -1));

        Pregunta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Pregunta.setForeground(new java.awt.Color(255, 255, 255));
        Pregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pregunta.setText("jLabel4");
        jPanel1.add(Pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 126, 260, 190));

        Op1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Op1.setForeground(new java.awt.Color(255, 255, 255));
        Op1.setText("Op1");
        Op1.setOpaque(false);
        jPanel1.add(Op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 270, -1));

        Op2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Op2.setForeground(new java.awt.Color(255, 255, 255));
        Op2.setText("Op2");
        Op2.setOpaque(false);
        jPanel1.add(Op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 270, -1));

        Op3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Op3.setForeground(new java.awt.Color(255, 255, 255));
        Op3.setText("Op3");
        Op3.setOpaque(false);
        jPanel1.add(Op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 270, -1));

        Op4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Op4.setForeground(new java.awt.Color(255, 255, 255));
        Op4.setText("Op4");
        Op4.setOpaque(false);
        jPanel1.add(Op4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 270, -1));

        Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/DesafioImagen/EnviarButton.png"))); // NOI18N
        Enviar.setBorderPainted(false);
        Enviar.setContentAreaFilled(false);
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        jPanel1.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/DesafioImagen/DesafioBackground.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
        if (Op1.isSelected()) {//validamos que la opcion elegita por esl usuario sea correcta
            if (opCorrecta == 0) {
                acierto = true;
            } else {
                acierto = false;
            }
        } else if (Op2.isSelected()) {
            if (opCorrecta == 1) {
                acierto = true;
            } else {
                acierto = false;
            }
        } else if (Op3.isSelected()) {
            if (opCorrecta == 2) {
                acierto = true;
            } else {
                acierto = false;
            }
        } else if (Op4.isSelected()) {
            if (opCorrecta == 3) {
                acierto = true;
            } else {
                acierto = false;
            }
        }
        this.dispose();
    }//GEN-LAST:event_EnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Desafios dialog = new Desafios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JRadioButton Op1;
    private javax.swing.JRadioButton Op2;
    private javax.swing.JRadioButton Op3;
    private javax.swing.JRadioButton Op4;
    private javax.swing.JLabel Pregunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
