/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectolabo;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author alexo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ButtonGroup group = new ButtonGroup();
    private Datos Datos;
    private ArrayList<Personaje> personajes;
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        userField.setForeground(new java.awt.Color(158,158,158));
        passField.setForeground(new java.awt.Color(158,158,158));
        group.add(jRadioButton1);
        group.add(jRadioButton2);
    }
    
    public Login(Datos Datos, ArrayList<Personaje> personajes) {
        initComponents();
        this.Datos = Datos;
        this.personajes = personajes;
        this.setLocationRelativeTo(null);
        userField.setForeground(new java.awt.Color(158,158,158));
        passField.setForeground(new java.awt.Color(158,158,158));
        group.add(jRadioButton1);
        group.add(jRadioButton2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        accederButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userField.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        userField.setForeground(new java.awt.Color(102, 102, 102));
        userField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userField.setText("Usuario");
        userField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFieldFocusLost(evt);
            }
        });
        jPanel1.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, -1));

        passField.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        passField.setForeground(new java.awt.Color(102, 102, 102));
        passField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passField.setText("Contraseña");
        passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFieldFocusLost(evt);
            }
        });
        jPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 250, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/LoginImagen/LoginLetras.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 520, -1));

        accederButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/LoginImagen/AccederButton.png"))); // NOI18N
        accederButton.setBorderPainted(false);
        accederButton.setContentAreaFilled(false);
        accederButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederButtonActionPerformed(evt);
            }
        });
        jPanel1.add(accederButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        regresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/LoginImagen/RegresarButton.png"))); // NOI18N
        regresarButton.setBorderPainted(false);
        regresarButton.setContentAreaFilled(false);
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(regresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Facil");
        jRadioButton1.setOpaque(false);
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 90, -1));

        jRadioButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Dificil");
        jRadioButton2.setOpaque(false);
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/LoginImagen/LoginBackground.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFieldFocusGained
        // TODO add your handling code here:
        if (userField.getText().equals("Usuario")) {
            userField.setText("");
            userField.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_userFieldFocusGained

    private void userFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFieldFocusLost
        // TODO add your handling code here:
        if (userField.getText().isEmpty()) {
            userField.setText("Usuario");
            userField.setForeground(new java.awt.Color(158,158,158));
        }
    }//GEN-LAST:event_userFieldFocusLost

    private void passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusGained
        // TODO add your handling code here:
        if (passField.getText().equals("Contraseña")) {
            passField.setText("");
            passField.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_passFieldFocusGained

    private void passFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusLost
        // TODO add your handling code here:
        if (passField.getText().isEmpty()) {
            passField.setText("Contraseña");
            passField.setForeground(new java.awt.Color(158,158,158)); // gris
        }
    }//GEN-LAST:event_passFieldFocusLost

    private void accederButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederButtonActionPerformed
        // TODO add your handling code here:
        String user = this.userField.getText();
        String pass = this.passField.getText();
        int p = Datos.verificaUser(user, pass);
        String seleccion = "";
        
        if(jRadioButton1.isSelected()){
            seleccion = "Facil";
        }else if(jRadioButton2.isSelected()){
            seleccion = "Dificil";
        }

        if(!user.isEmpty() && !pass.isEmpty() && !seleccion.isEmpty()){//validamos que se hayan llenado los dos campos
            if(p >= 0){//si encontro al jugador llama a la ventana de juego
                
                ArrayList<Jugador> jugadores = Datos.getArray_jugadores();
                
                for(Jugador e : jugadores){
                    if(user.equals(e.getUser())){
                       new SeleccionPersonaje(personajes, e,seleccion,Datos).setVisible(true);
                    }
                }
                this.dispose();
            }else if(p == -1){//si encontro al usuario pero no es la contraseña correcta manda una advertencia
                JOptionPane.showMessageDialog(null, "Vuelve a introducir la contraseña","INFORMATION_MESSAGE",JOptionPane.INFORMATION_MESSAGE);
            }else{//si no encontro al usuario llama a la ventana de registro
                new Registro(Datos,personajes).setVisible(true);
                this.dispose();
            }
        }else{//si no se llenaron los espacios manda una advertencia
            JOptionPane.showMessageDialog(null, "Llena todos los espacios","INFORMATION_MESSAGE",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_accederButtonActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        // TODO add your handling code here:
        new Menu(Datos).setVisible(true);//regresa a la ventana de menu
        this.dispose();
    }//GEN-LAST:event_regresarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accederButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField passField;
    private javax.swing.JButton regresarButton;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
