/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectolabo;

import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author alexo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Datos Datos;
    
    public Menu() {
        initComponents();
        
        setLocationRelativeTo(null);
    }
    
    public Menu(Datos datos){
        initComponents();
        this.Datos = datos;//recibimos el objeto Datos y lo guardamos
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JugarButton = new javax.swing.JButton();
        ReporteButton = new javax.swing.JButton();
        AyudaButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JugarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/MenuImagen/JugarButton.png"))); // NOI18N
        JugarButton.setBorderPainted(false);
        JugarButton.setContentAreaFilled(false);
        JugarButton.setFocusPainted(false);
        JugarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(JugarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        ReporteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/MenuImagen/ReporteButton.png"))); // NOI18N
        ReporteButton.setBorderPainted(false);
        ReporteButton.setContentAreaFilled(false);
        ReporteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ReporteButton.setFocusPainted(false);
        ReporteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ReporteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        AyudaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/MenuImagen/AyudaButton.png"))); // NOI18N
        AyudaButton.setBorderPainted(false);
        AyudaButton.setContentAreaFilled(false);
        AyudaButton.setFocusPainted(false);
        AyudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AyudaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        SalirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/MenuImagen/SalirButton.png"))); // NOI18N
        SalirButton.setBorderPainted(false);
        SalirButton.setContentAreaFilled(false);
        SalirButton.setFocusPainted(false);
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SalirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/MenuImagen/MenuBackground.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JugarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Personaje> Personajes = new ArrayList<>();//creamos a los personajes usandola URL necesarias de cada uno.
        
        Personajes.add(new Personaje("Ash","/proyectolabo/PersonajesImagenes/p1.1.png","/proyectolabo/PersonajesImagenes/p1.2.png","/proyectolabo/PersonajesImagenes/p1.3.png","/proyectolabo/PersonajesImagenes/p1.4.png"
        ,"/proyectolabo/PersonajesImagenes/p1.1_1.png","/proyectolabo/PersonajesImagenes/p1.2_1.png","/proyectolabo/PersonajesImagenes/p1.3_1.png","/proyectolabo/PersonajesImagenes/p1.4_1.png"
        ,"/proyectolabo/PersonajesImagenes/p1.1_2.png","/proyectolabo/PersonajesImagenes/p1.2_2.png","/proyectolabo/PersonajesImagenes/p1.3_2.png","/proyectolabo/PersonajesImagenes/p1.4_2.png"));
        
        Personajes.add(new Personaje("Maya","/proyectolabo/PersonajesImagenes/p2.1.png","/proyectolabo/PersonajesImagenes/p2.2.png","/proyectolabo/PersonajesImagenes/p2.3.png","/proyectolabo/PersonajesImagenes/p2.4.png"
        ,"/proyectolabo/PersonajesImagenes/p2.1_1.png","/proyectolabo/PersonajesImagenes/p2.2_1.png","/proyectolabo/PersonajesImagenes/p2.3_1.png","/proyectolabo/PersonajesImagenes/p2.4_1.png"
        ,"/proyectolabo/PersonajesImagenes/p2.1_2.png","/proyectolabo/PersonajesImagenes/p2.2_2.png","/proyectolabo/PersonajesImagenes/p2.3_2.png","/proyectolabo/PersonajesImagenes/p2.4_2.png"));
        
        Personajes.add(new Personaje("Brock","/proyectolabo/PersonajesImagenes/p3.1.png","/proyectolabo/PersonajesImagenes/p3.2.png","/proyectolabo/PersonajesImagenes/p3.3.png","/proyectolabo/PersonajesImagenes/p3.4.png"
        ,"/proyectolabo/PersonajesImagenes/p3.1_1.png","/proyectolabo/PersonajesImagenes/p3.2_1.png","/proyectolabo/PersonajesImagenes/p3.3_1.png","/proyectolabo/PersonajesImagenes/p3.4_1.png"
        ,"/proyectolabo/PersonajesImagenes/p3.1_2.png","/proyectolabo/PersonajesImagenes/p3.2_2.png","/proyectolabo/PersonajesImagenes/p3.3_2.png","/proyectolabo/PersonajesImagenes/p3.4_2.png"));
        
        Personajes.add(new Personaje("Iris","/proyectolabo/PersonajesImagenes/p4.1.png","/proyectolabo/PersonajesImagenes/p4.2.png","/proyectolabo/PersonajesImagenes/p4.3.png","/proyectolabo/PersonajesImagenes/p4.4.png"
        ,"/proyectolabo/PersonajesImagenes/p4.1_1.png","/proyectolabo/PersonajesImagenes/p4.2_1.png","/proyectolabo/PersonajesImagenes/p4.3_1.png","/proyectolabo/PersonajesImagenes/p4.4_1.png"
        ,"/proyectolabo/PersonajesImagenes/p4.1_2.png","/proyectolabo/PersonajesImagenes/p4.2_2.png","/proyectolabo/PersonajesImagenes/p4.3_2.png","/proyectolabo/PersonajesImagenes/p4.4_2.png"));
        
        new Login(this.Datos, Personajes).setVisible(true);//llamamos al JFrame Login pasandole datos y persoajes
        this.dispose();
    }//GEN-LAST:event_JugarButtonActionPerformed

    private void ReporteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteButtonActionPerformed
        // TODO add your handling code here:
        if(!Datos.getArray_jugadores().isEmpty()){//si tiene jugadores disponibles los imprime junto a su informacion en el JDialog reporte
            Reporte dialog = new Reporte(new javax.swing.JFrame(), true, Datos);
            dialog.setVisible(true);
        }else{//si no hay jugadores manda un mensaje diciendo que no existen
            JOptionPane.showMessageDialog(null, "No hay jugadores registrados","INFORMATION_MESSAGE",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ReporteButtonActionPerformed

    private void AyudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaButtonActionPerformed
        // TODO add your handling code here:
        new Ayuda(Datos).setVisible(true);//llamamos al JFrame Ayuda pasandole el objeto datos para no perderlo de vista.
        this.dispose();
    }//GEN-LAST:event_AyudaButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);//salimos del programa.
    }//GEN-LAST:event_SalirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AyudaButton;
    private javax.swing.JButton JugarButton;
    private javax.swing.JButton ReporteButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
