/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectolabo;

/**
 *
 * @author alexo
 */
public class Pausa extends javax.swing.JDialog {

    /**
     * Creates new form Pausa
     */
    private Jugador jugador;
    private Datos datos;
    private String dificultad;
    private int[][] mapa;
    private String fecha;
    private String hora;
    private boolean teclaW;
    private boolean teclaZ;
    private boolean teclaQ;
    private boolean teclaV;
    
    public Pausa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public Pausa(java.awt.Frame parent, boolean modal, Jugador jugador,Datos datos, String dificultad, int[][] mapa, String fecha, String hora,
            boolean teclaW, boolean teclaZ, boolean teclaQ, boolean teclaV) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        this.jugador = jugador;
        this.datos = datos;
        this.dificultad = dificultad;
        this.mapa = mapa;
        this.fecha = fecha;
        this.hora = hora;
        this.teclaW = teclaW;
        this.teclaZ = teclaZ;
        this.teclaQ = teclaQ;
        this.teclaV = teclaV;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SalirButton = new javax.swing.JButton();
        ReanudarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pausa");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/PausaImagen/Salir-removebg-preview.png"))); // NOI18N
        SalirButton.setBorderPainted(false);
        SalirButton.setContentAreaFilled(false);
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SalirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        ReanudarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/PausaImagen/ReanudarButton__2_-removebg-preview.png"))); // NOI18N
        ReanudarButton.setBorderPainted(false);
        ReanudarButton.setContentAreaFilled(false);
        ReanudarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReanudarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ReanudarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/PausaImagen/FondoPausa.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReanudarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReanudarButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Laberinto(this.jugador, this.dificultad, this.datos, this.mapa,fecha,hora,this.teclaW,this.teclaZ,this.teclaQ,this.teclaV).setVisible(true);
    }//GEN-LAST:event_ReanudarButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new PAUSAROGANAR(jugador.getUser(), datos, this.fecha, this.hora).setVisible(true);
    }//GEN-LAST:event_SalirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pausa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pausa dialog = new Pausa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReanudarButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
