/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectolabo;

import java.text.*;
import java.util.*;

/**
 *
 * @author alexo
 */
public class PERDEROGANAR extends javax.swing.JFrame {

    /**
     * Creates new form PERDEROGANAR
     */
    private int puntos;
    private int vidas;
    private String nombre;
    private Datos datos;
    private String fecha;
    private String horaI;
    
    public PERDEROGANAR() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public PERDEROGANAR(int puntos, int vidas, String nombre, Datos datos, String fecha, String horaI) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.puntos = puntos;
        this.vidas = vidas;
        this.nombre = nombre;
        this.datos = datos;
        this.fecha = fecha;
        this.horaI = horaI;
        
        setLabelVidas();
        setPuntosLabel();
        setNombre();
        
        for(Jugador e : datos.getArray_jugadores()){//buscamos al usuario que jugo la partida e insertamos los puntosmaximo en la BD
            if(nombre.equals(e.getUser())){
                if(e.getPuntuacionMax() < puntos){
                    e.setPuntuacionMax(puntos);
                }
                datos.insertarPuntuacion(e.getUser(), e.getPuntuacionMax());
            }
        }
        
        Date hora = new Date();//buscamos la hora en la que se perdio la partida
        DateFormat formato = new SimpleDateFormat("HH:mm:ss a");
        
        String horaF = formato.format(hora);
        String estado = "Perdido";
        
        Partida partida = new Partida(nombre,horaI,fecha,horaF,estado);//insertamos la partida en la BD
        
        datos.agregarPartida(partida);
    }
    
    private void setLabelVidas() {
        this.LabelVidas.setText(""+vidas);
    }

    private void setPuntosLabel() {
        this.PuntosLabel.setText(""+puntos);
    }
    
    private void setNombre(){
        this.Consuelo.setText("¡MEJOR SUERTE LA PROXIMA: "+this.nombre+"!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Consuelo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelVidas = new javax.swing.JLabel();
        PuntosLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perder");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/PerderImagen/MenuButton.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 400, 170, -1));

        Consuelo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Consuelo.setForeground(new java.awt.Color(255, 255, 255));
        Consuelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Consuelo.setText("jLabel2");
        jPanel1.add(Consuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 250, 480, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/PerderImagen/Corazon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/PerderImagen/Puntuacion.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        LabelVidas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LabelVidas.setForeground(new java.awt.Color(255, 255, 255));
        LabelVidas.setText("jLabel4");
        jPanel1.add(LabelVidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 351, 160, 30));

        PuntosLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        PuntosLabel.setForeground(new java.awt.Color(255, 255, 255));
        PuntosLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PuntosLabel.setText("jLabel4");
        jPanel1.add(PuntosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 350, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/PerderImagen/PerderBackground.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu(datos).setVisible(true);//llamamos al JFrame menu
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PERDEROGANAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PERDEROGANAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PERDEROGANAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PERDEROGANAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PERDEROGANAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Consuelo;
    private javax.swing.JLabel LabelVidas;
    private javax.swing.JLabel PuntosLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
