/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectolabo;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author alexo
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    ButtonGroup group = new ButtonGroup();
    private Datos Datos;
    private ArrayList<Personaje> personajes;
    
    public Registro() {
        initComponents();
        nombreField.setForeground(new java.awt.Color(158,158,158));
        userField.setForeground(new java.awt.Color(158,158,158));
        passField1.setForeground(new java.awt.Color(158,158,158));
        passField2.setForeground(new java.awt.Color(158,158,158));
        group.add(jRadioButton1);
        group.add(jRadioButton2);
        this.setLocationRelativeTo(null);
    }
    
    public Registro(Datos Datos, ArrayList<Personaje> personajes) {
        initComponents();
        nombreField.setForeground(new java.awt.Color(158,158,158));
        userField.setForeground(new java.awt.Color(158,158,158));
        passField1.setForeground(new java.awt.Color(158,158,158));
        passField2.setForeground(new java.awt.Color(158,158,158));
        this.Datos = Datos;
        this.personajes = personajes;
        group.add(jRadioButton1);
        group.add(jRadioButton2);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreField = new javax.swing.JTextField();
        userField = new javax.swing.JTextField();
        passField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSlider1 = new javax.swing.JSlider();
        muestraEdad = new javax.swing.JLabel();
        registrarButton = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreField.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nombreField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreField.setText("Nombre");
        nombreField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFieldFocusLost(evt);
            }
        });
        jPanel1.add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, -1));

        userField.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        userField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userField.setText("Usuario");
        userField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFieldFocusLost(evt);
            }
        });
        jPanel1.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, -1));

        passField1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        passField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passField1.setText("Contraseña");
        passField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passField1FocusLost(evt);
            }
        });
        jPanel1.add(passField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/RegistroImagen/RegistroLetras.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, -1));

        passField2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        passField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passField2.setText("Contraseña");
        passField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passField2FocusLost(evt);
            }
        });
        jPanel1.add(passField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 220, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 190, 10));

        jRadioButton1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Hombre");
        jRadioButton1.setOpaque(false);
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Mujer");
        jRadioButton2.setOpaque(false);
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 190, 10));

        jSlider1.setMaximum(64);
        jSlider1.setMinimum(14);
        jSlider1.setPaintLabels(true);
        jSlider1.setValue(14);
        jSlider1.setOpaque(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, 30));

        muestraEdad.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        muestraEdad.setForeground(new java.awt.Color(255, 255, 255));
        muestraEdad.setText("Edad");
        muestraEdad.setToolTipText("");
        jPanel1.add(muestraEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        registrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/RegistroImagen/Registrarboton.png"))); // NOI18N
        registrarButton.setBorderPainted(false);
        registrarButton.setContentAreaFilled(false);
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/RegistroImagen/Regresarboton.png"))); // NOI18N
        regresar.setBorderPainted(false);
        regresar.setContentAreaFilled(false);
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/RegistroImagen/RegistroBackground.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFieldFocusGained
        // TODO add your handling code here:
        if (nombreField.getText().equals("Nombre")) {
            nombreField.setText("");
            nombreField.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_nombreFieldFocusGained

    private void nombreFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFieldFocusLost
        // TODO add your handling code here:
        if (nombreField.getText().isEmpty()) {
            nombreField.setText("Nombre");
            nombreField.setForeground(new java.awt.Color(158,158,158));
        }
    }//GEN-LAST:event_nombreFieldFocusLost

    private void userFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFieldFocusGained
        // TODO add your handling code here:
        if (userField.getText().equals("Usuario")) {
            userField.setText("");
            userField.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_userFieldFocusGained

    private void userFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFieldFocusLost
        // TODO add your handling code here:
        if (userField.getText().isEmpty()) {
            userField.setText("Usuario");
            userField.setForeground(new java.awt.Color(158,158,158));
        }
    }//GEN-LAST:event_userFieldFocusLost

    private void passField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField1FocusGained
        // TODO add your handling code here:
        if (passField1.getText().equals("Contraseña")) {
            passField1.setText("");
            passField1.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_passField1FocusGained

    private void passField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField1FocusLost
        // TODO add your handling code here:
        if (passField1.getText().isEmpty()) {
            passField1.setText("Contraseña");
            passField1.setForeground(new java.awt.Color(158,158,158));
        }
    }//GEN-LAST:event_passField1FocusLost

    private void passField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField2FocusGained
        // TODO add your handling code here:
        if (passField2.getText().equals("Contraseña")) {
            passField2.setText("");
            passField2.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_passField2FocusGained

    private void passField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField2FocusLost
        // TODO add your handling code here:
        if (passField2.getText().isEmpty()) {
            passField2.setText("Contraseña");
            passField2.setForeground(new java.awt.Color(158,158,158));
        }
    }//GEN-LAST:event_passField2FocusLost

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        this.muestraEdad.setText(Integer.toString(this.jSlider1.getValue()));
    }//GEN-LAST:event_jSlider1StateChanged

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
        // TODO add your handling code here:
        String nombre = this.nombreField.getText();
        String user = this.userField.getText();
        String pass1 = this.passField1.getText();
        String pass2 = this.passField2.getText();
        String edad = Integer.toString(this.jSlider1.getValue());
        String sexo = "";

        if (jRadioButton1.isSelected()) {//si se eligio la opcion de H se guarda q es hombre
            sexo = "Hombre";
        } else if (jRadioButton2.isSelected()) {//si se eligio la opcion M se guarda que es mujer
            sexo = "Mujer";
        }

        if(!nombre.isEmpty() && !user.isEmpty() && !pass1.isEmpty() && !pass2.isEmpty() && !edad.isEmpty() && !sexo.isEmpty()){//valida que todos los espacios esten llenos
            if(pass1.equals(pass2)){//valida que las contraseñas escritas sean iguales
                Jugador jugador = new Jugador(nombre,edad,sexo,user,pass1,0);//crea al jugador y lo almacena en el arrayList de datos
                Datos.agregaJugador(jugador);
                JOptionPane.showMessageDialog(null, "Haz sido registrado","INFORMATION_MESSAGE",JOptionPane.INFORMATION_MESSAGE);//confirma el registro
                new Login(this.Datos,this.personajes).setVisible(true);//regresa a la ventana de login
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Contraseña diferente","INFORMATION_MESSAGE",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Llena todos los campos","INFORMATION_MESSAGE",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        new Login(this.Datos,this.personajes).setVisible(true);//llamamos al JFrame Login
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel muestraEdad;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField passField1;
    private javax.swing.JTextField passField2;
    private javax.swing.JButton registrarButton;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
