/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectolabo;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author alexo
 */
public class SeleccionPersonaje extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionPersonaje
     */
    private int posicion;
    private ArrayList<Personaje> personajes;
    private Animacion animacion;
    private Jugador jugador;
    private String dificultad;
    private Datos datos;
    
    public SeleccionPersonaje() {
        initComponents();
    }
    
    public SeleccionPersonaje(ArrayList<Personaje> personajes, Jugador jugador, String dificultad, Datos datos) {
        initComponents();
        this.personajes = personajes;
        this.jugador = jugador;
        this.dificultad = dificultad;
        this.datos = datos;
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        getContentPane().setBackground(new Color(182, 177, 202));
        jPanel1.setBackground(new Color(182, 177, 202));
        
        Izquierda.setBorderPainted(false);
        Izquierda.setContentAreaFilled(false);
        Izquierda.setFocusPainted(false);
        Izquierda.setOpaque(false);
        
        Derecha.setBorderPainted(false);
        Derecha.setContentAreaFilled(false);
        Derecha.setFocusPainted(false);
        Derecha.setOpaque(false);
        
        START.setBorderPainted(false);
        START.setContentAreaFilled(false);
        START.setFocusPainted(false);
        START.setOpaque(false);
        
        PanelPersonaje.setLayout(new BorderLayout());
        PanelPersonaje.setPreferredSize(new Dimension(156, 110));
        
        animacion = new Animacion(personajes.get(posicion).getImagenAbajoSeleccion(),156,110,4);
        
        PanelPersonaje.add(animacion,BorderLayout.CENTER);
        PanelPersonaje.revalidate();
        PanelPersonaje.repaint();
        
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelPersonaje = new javax.swing.JPanel();
        Derecha = new javax.swing.JButton();
        Izquierda = new javax.swing.JButton();
        START = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccionar personaje");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPersonaje.setOpaque(false);

        javax.swing.GroupLayout PanelPersonajeLayout = new javax.swing.GroupLayout(PanelPersonaje);
        PanelPersonaje.setLayout(PanelPersonajeLayout);
        PanelPersonajeLayout.setHorizontalGroup(
            PanelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanelPersonajeLayout.setVerticalGroup(
            PanelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(PanelPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        Derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/SeleccionImagen/Derecha.png"))); // NOI18N
        Derecha.setBorderPainted(false);
        Derecha.setContentAreaFilled(false);
        Derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerechaActionPerformed(evt);
            }
        });
        jPanel1.add(Derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        Izquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/SeleccionImagen/Izquierda.png"))); // NOI18N
        Izquierda.setToolTipText("");
        Izquierda.setBorderPainted(false);
        Izquierda.setContentAreaFilled(false);
        Izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzquierdaActionPerformed(evt);
            }
        });
        jPanel1.add(Izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        START.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/SeleccionImagen/SeleccionarButton_1.png"))); // NOI18N
        START.setBorderPainted(false);
        START.setContentAreaFilled(false);
        START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STARTActionPerformed(evt);
            }
        });
        jPanel1.add(START, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/SeleccionImagen/PersonajesLetras.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolabo/SeleccionImagen/seleccionBackground.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzquierdaActionPerformed
        // TODO add your handling code here:
        if(posicion <= 0){//cambiamos al personaje mostrado en pantalla
            posicion = 3;
        }else{
            posicion--;
        }
        
        PanelPersonaje.removeAll();
        animacion.setImg(personajes.get(posicion).getImagenAbajoSeleccion());
        PanelPersonaje.add(animacion,BorderLayout.CENTER);
        PanelPersonaje.revalidate();
        PanelPersonaje.repaint();
    }//GEN-LAST:event_IzquierdaActionPerformed

    private void DerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerechaActionPerformed
        // TODO add your handling code here:
        if(posicion >= 3){//cambiamos al personaje mostrado en pantalla
            posicion = 0;
        }else{
            posicion++;
        }
        
        PanelPersonaje.removeAll();
        animacion.setImg(personajes.get(posicion).getImagenAbajoSeleccion());
        PanelPersonaje.add(animacion,BorderLayout.CENTER);
        PanelPersonaje.revalidate();
        PanelPersonaje.repaint();
    }//GEN-LAST:event_DerechaActionPerformed

    private void STARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STARTActionPerformed
        // TODO add your handling code here:
        this.jugador.setPersonaje(personajes.get(posicion));//seleccionamos al personaje y lo guardamos
        
        new Laberinto(jugador,dificultad,datos).setVisible(true);//llamamos al JFrame del laberinto
        
        this.dispose();
    }//GEN-LAST:event_STARTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Derecha;
    private javax.swing.JButton Izquierda;
    private javax.swing.JPanel PanelPersonaje;
    private javax.swing.JButton START;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
